site_name: x2rs的小站
site_url: https://x2rs.github.io
site_author: x2rs
site_description: My personal documentation website.

nav:
  - 主页:
    - index.md
    - todo.md
  - 笔记:
    - notes/Cramer-Rao.md
    - notes/physics.md
    - notes/order-of-destructor-calls.md
    - notes/strong-and-weak-symbol.md
    - notes/cpp-derived-class-access.md
    - notes/regex.md
    - notes/python-venv.md
  - 杂项:
    - matlab/simple_linear.md
    - useful_apps.md
  - Learn Intern LM:
    - learn-lm/intern-lm-1.md

theme:
  name: material
  # [给每个页面添加giscus]
  # https://github.com/x2rs/x2rs.github.io/issues/6
  custom_dir: overrides
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: indigo
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  language: zh # 一些提示性的文字会变成中文

  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    # [点击按钮跳转至 GitHub 查看 Markdown 源代码]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.view

# [显示页面修改日期]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=revision+date#document-dates
plugins:
  # [搜索功能]
  # 注意：如果在配置文件中还没有 plugins 条目，您可能还想添加 search 插件。MkDocs 在没有设置 plugins 条目时默认启用搜索功能，但现在您需要显式启用它。
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date

# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/x2rs/x2rs.github.io
repo_name: x2rs.github.io

markdown_extensions:
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  # [任务清单勾选框]
  # https://squidfunk.github.io/mkdocs-material/reference/lists/#configuration
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js