name: publish site
on: # 在什么时候触发工作流
  push: # 在从本地main分支被push到GitHub仓库时
    branches:
      - main
jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-latest # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    steps:
      - uses: actions/checkout@v4 # 先checkout到main分支
        with:
          fetch-depth: 0  # 将fetch depth 设置为 0
      - uses: actions/setup-python@v5 # 再安装Python3和相关环境
        with:
          python-version: 3.x
      - run: pip install mkdocs-material # 使用pip包管理工具安装mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin # 页面的修改时间
      - run: mkdocs gh-deploy --force # 使用mkdocs-material部署gh-pages分支
